#!/bin/bash

ORCL=${DB_PORT_1521_TCP_ADDR}:${DB_PORT_1521_TCP_PORT}:${DB_ENV_ORACLE_SID}
DATABASE=/app/ismobile/jboss-4.2.3.GA/server/coord/coordConfig/database
HPADMIN="java -cp ${DATABASE}/oracle-libs/ojdbc7.jar:${DATABASE}/ism_tools/hpadmin-R2.1.20.jar com.ismobile.hpadmin.Main"

CMD="${HPADMIN} --url=jdbc:oracle:thin:coord/coord@${ORCL} --dataset --map --heapname=DEFAULT $1"

echo $CMD

$CMD
